export default [
    {
        title: "AlvitaNutrition",
        image: "",
        short_desc: "Pharmaceutical Ecommerce and Blogging Website",
        live_link: "https://alvitanutrition.com",
        technologies: ["Next.js", "React.js", "Laravel", "Git", "Figma"],
    },
    {
        title: "IBCCITIZENS",
        image: "",
        short_desc: "A crypto project community website",
        live_link: "https://ibccitizens.com",
        technologies: ["React.js", "Laravel", "Git"],
    },
    {
        title: "Viral Snare",
        image: "",
        short_desc: "A media sharing and streaming website",
        live_link: "https://viralsnare.com",
        technologies: ["React.js", "Laravel", "Git"],
    },
    {
        title: "SJCommerce",
        image: "",
        short_desc: "Ecommerce android app",
        live_link:
            "https://play.google.com/store/apps/details?id=com.sjcommerce.com",
        technologies: ["React Native", "Expo", "WordPress", "Git"],
    },
    {
        title: "CyberLinio",
        image: "",
        short_desc: "Ecommerce mobile app",
        project_link: "https://github.com/KawshikBss/CyberLinio",
        technologies: ["React Native", "Expo", "Git"],
    },
    {
        title: "TodoDaily",
        image: "",
        short_desc: "A todo management website",
        project_link: "https://github.com/KawshikBss/tododaily",
        technologies: [
            "MongoDB",
            "Express.js",
            "React.js",
            "Node.js",
            "Passport.js",
            "Mongoose.js",
            "EJS",
        ],
    },
    {
        title: "AlgoViz",
        image: "",
        short_desc: "Pathfinding algorithm visualizer",
        live_link: "https://kawshikbss.github.io/AlgoViz/ ",
        technologies: ["React.js", "Git", "GitHub Pages"],
    },
    {
        title: "Gate Blogs",
        image: "",
        short_desc: "Blogging website",
        project_link: "https://github.com/KawshikBss/gates-blogs",
        technologies: ["Laravel", "Git", "Figma"],
    },
    {
        title: "CrptoMarket",
        image: "",
        short_desc: "A NFT minting website",
        project_link: "https://github.com/KawshikBss/CryptoMarket",
        technologies: [
            "React.js",
            "Solidity",
            "Hardhat",
            "Pinata",
            "Git",
            "Figma",
        ],
    },
];
